#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -font 'mononoki Nerd Font 12' -xoffset -10 -yoffset -40 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "Lock|Logout|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen -s;;
                *Logout) i3-msg exit;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
