#!/bin/bash

#  ____  _   _ 
# |  _ \| \ | | Pradyun Narkadamilli
# | |_) |  \| | https://pradyungn.tech
# |  __/| |\  | MIT License
# |_|   |_| \_| Copyright 2021 Pradyun Narkadamilli

#
# Keybinding Portion of HLWM config
#

# Function to make commands less annoying
hc() {
    herbstclient "$@"
}


TERMINAL=alacritty

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4 

# basic action
hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload

# terminals
hc keybind $Mod-Return spawn "${TERMINAL:-xterm}"
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-xterm}" --class floating_term,floating_term
hc keybind $Mod-Ctrl-Return spawn "${TERMINAL:-xterm}" --class teeny_term,teeny_term

# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# focus
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-c cycle -1
hc keybind $Mod-i jumpto urgent

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# create an empty frame at the specified direction
hc keybind $Mod-Ctrl-j spawn ~/.config/herbstluftwm/scripts/split bottom
hc keybind $Mod-Ctrl-h spawn ~/.config/herbstluftwm/scripts/split left
hc keybind $Mod-Ctrl-k spawn ~/.config/herbstluftwm/scripts/split top
hc keybind $Mod-Ctrl-l spawn ~/.config/herbstluftwm/scripts/split right

# selecting split ratio
echo 0.5 > ~/.config/herbstluftwm/ratio
for boomer in {1..9}; do
    hc keybind $Mod-Ctrl-$boomer spawn ~/.config/herbstluftwm/scripts/ratioset "0.$boomer"
done

# frame invisibility toggle
hc keybind $Mod-v set frame_bg_transparent toggle


# let the current frame explode into subframes
hc keybind $Mod-Ctrl-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Alt-h       resize left +$resizestep
hc keybind $Mod-Alt-j       resize down +$resizestep
hc keybind $Mod-Alt-k       resize up +$resizestep
hc keybind $Mod-Alt-l       resize right +$resizestep

# tags
tag_names=( "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-Alt-$key" use_index "$i"
        hc keybind "$Mod-Alt-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-p pseudotile toggle

# restore all minimized windows of the focused tag
hc keybind $Mod-Ctrl-m foreach CLIENT clients. \
     sprintf MINATT "%c.minimized" CLIENT \
     sprintf TAGATT "%c.tag" CLIENT and \
       , compare MINATT "=" "true" \
       , substitute FOCUS "tags.focus.name" compare TAGATT "=" FOCUS \
       , set_attr MINATT false

# The following cycles through the available layouts within a frame
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# night mode
hc keybind $Mod-Ctrl-r spawn ~/.config/herbstluftwm/scripts/nightmode

# rofi bs
hc keybind $Mod-d spawn rofi -show drun -location 1 -xoffset 20 -yoffset 20 -columns 1 -width 10 -lines 5
hc keybind $Mod-w spawn rofi -show window -location 1 -xoffset 20 -yoffset 20 -width 18 -lines 5
hc keybind $Mod-m spawn ~/.config/herbstluftwm/scripts/mpc_rof
hc keybind $Mod-b spawn ~/.config/herbstluftwm/scripts/bctl
hc keybind $Mod-t spawn ~/.config/herbstluftwm/scripts/tmxui
hc keybind $Mod-Shift-p spawn ~/.config/herbstluftwm/scripts/power

# special keys
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5

hc keybind XF86AudioPlayPause spawn ~/.config/herbstluftwm/scripts/media play-pause
hc keybind $Mod-8 spawn ~/.config/herbstluftwm/scripts/media play-pause

hc keybind XF86AudioPlay spawn ~/.config/herbstluftwm/scripts/media play
hc keybind XF86AudioPause spawn ~/.config/herbstluftwm/scripts/media pause

hc keybind XF86AudioNext spawn ~/.config/herbstluftwm/scripts/media next
hc keybind $Mod-0 spawn ~/.config/herbstluftwm/scripts/media next

hc keybind XF86AudioPrev spawn ~/.config/herbstluftwm/scripts/media previous
hc keybind $Mod-9 spawn ~/.config/herbstluftwm/scripts/media previous

hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind $Mod-Shift-8 spawn pactl set-sink-mute @DEFAULT_SINK@ toggle

hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind $Mod-Shift-0 spawn pactl set-sink-volume @DEFAULT_SINK@ +5%

hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -5%
hc keybind $Mod-Shift-9 spawn pactl set-sink-volume @DEFAULT_SINK@ -5%

# screenshots
hc keybind Print spawn scrot -e 'mv $f ~/Pictures/Screenshots'
hc keybind $Mod-Print spawn scrot -u -b -e 'mv $f ~/Pictures/Screenshots'
hc keybind $Mod-Ctrl-Print spawn flameshot gui

# applications
hc keybind $Mod-1 spawn discord
hc keybind $Mod-2 spawn qutebrowser
hc keybind $Mod-3 spawn "${TERMINAL:-xterm}" -e 'ranger'
hc keybind $Mod-4 spawn "${TERMINAL:-xterm}" -e 'gotop'
hc keybind $Mod-5 spawn "${TERMINAL:-xterm}" -e 'ncmpcpp'

hc keybind $Mod-n spawn notion-app-nativefier

hc keybind $Mod-Ctrl-p spawn pavucontrol

hc keybind $Mod-e spawn emacs

# EWW launcher
hc keybind $Mod-Shift-d spawn ~/.config/herbstluftwm/scripts/launcher
