#!/bin/bash

#  ____  _   _ 
# |  _ \| \ | | Pradyun Narkadamilli
# | |_) |  \| | https://pradyungn.tech
# |  __/| |\  | MIT License
# |_|   |_| \_| Copyright 2021 Pradyun Narkadamilli

#
# Theme Portion of HLWM config
#

# Function to make commands less annoying
hc() {
    herbstclient "$@"
}

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#262626'
hc set frame_border_normal_color '#191919'
hc set frame_bg_normal_color '#262626'
hc set frame_bg_active_color '#191919'
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 20

hc attr theme.title_height 0
hc attr theme.padding_top 0 
hc attr theme.active.color '#262626'
hc attr theme.normal.color '#262626'
hc attr theme.urgent.color #ac8a8c
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 5
hc attr theme.floating.border_width 0
hc attr theme.floating.padding_top 20
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color "#262626"
hc attr theme.active.inner_color '#262626'
hc attr theme.active.outer_color '#262626'
hc attr theme.background_color '#262626'

hc set window_gap 5
hc set frame_padding -5
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

