#!/usr/bin/bash

IFS=$'\n'
count=5
format=$(cat ~/.config/eww/data/ewwmenu_config | grep -m 1 -oP "(?<=Format=).*")
s=0

xml='<box orientation="v" class="results" space-evenly="false">'
if [[ ! -z $1 ]]; then
    for i in $(ls /usr/share/applications/ | grep -i "$1" | grep ".*.desktop"); do
        if [[ $s -eq $count ]]; then
            break 1
        fi
        elem=$(cat "/usr/share/applications/"$i)
        name=$(echo "$elem" | grep -m 1 -oP "(?<=Name=).*")
        comment=$(echo "$elem" | grep -m 1 -oP "(?<=GenericName=).*")
        execute=($(echo "$elem" | grep -m 1 -oP "(?<=Exec=).*")" &")
        final="$(eval "echo $format")"
        xml+="${final//\&/\&amp;}"
        let "s+=1"  
    done
else
    for i in $(cat .config/eww/data/ewwdefaults); do
        if [[ $s -eq $count ]]; then
            break 1
        fi
        elem=""
        for i in $(ls /usr/share/applications/ | grep -i "$i" | grep ".*.desktop"); do
            elem=$(echo "/usr/share/applications/$i")
            break 1
        done
        name=$(cat "$elem" | grep -m 1 -oP "(?<=Name=).*")
        comment=$(cat "$elem" | grep -m 1 -oP "(?<=GenericName=).*")
        execute=($(cat "$elem" | grep -m 1 -oP "(?<=Exec=).*")" &")
        final="$(eval "echo $format")"
        xml+="${final//\&/\&amp;}"
        let "s+=1"  
    done
fi
xml+="</box>"
eww update buttonxml="$xml"
