#!/bin/bash

if [  "$(pgrep -x spotify)" ]; then
    player="Spotify"
elif [ "$(pgrep -x spt)" ]; then
    player="RemoteSpotify"
else
    player="Music Player Daemon"
fi

~/.config/eww/scripts/mpris_data "$player"
