#!/bin/sh

apikey="5ef4c2e248c008bcbca60c495d45ec14"
city_id="5392593"

declare -A icons=( ["01d"]="" ["01n"]="" ["02d"]="" ["02n"]="" ["03d"]="" ["03n"]="" ["04d"]="" ["04n"]="" ["09d"]="" ["09n"]="" ["10d"]="" ["10n"]="" ["11d"]="" ["11n"]="" ["13d"]="" ["13n"]="" ["50d"]="" ["50n"]="")

weather=$(curl -sf "https://api.openweathermap.org/data/2.5/weather?id=$city_id&appid=$apikey&units=imperial")
weather_desc=$(echo $weather | jq -r ".weather[0].main")
icon=$(echo $weather | jq -r ".weather[0].icon")
weather_temp=$(echo $weather | jq ".main.temp" | cut -d "." -f 1)
feels_like=$(echo $weather | jq ".main.feels_like" | cut -d "." -f 1)
humidity=$(echo $weather | jq ".main.humidity")
wind=$(echo $weather | jq ".wind.speed")

echo "$weather_temp" > ~/.config/eww/data/temp
echo $feels_like > ~/.config/eww/data/feeling
echo $humidity > ~/.config/eww/data/humidity
echo $wind > ~/.config/eww/data/wind
echo "$weather_desc"

echo $icon > ~/.config/eww/data/icon_code
echo "${icons[$icon]}" > ~/.config/eww/data/icon
