[Variables]
Main_FG =E9E9F4
Secondary_FG =DEDEDE
Main_BG =282936
Sidebar_And_Player_BG =282936
Cover_Overlay_And_Shadow =000000
Indicator_FG_And_Button_BG =4D4F68
Pressing_FG = FF5C86
Slider_BG =3A3C4E
Sidebar_Indicator_And_Hover_Button_BG =E9E9F4
Scrollbar_FG_And_Selected_Row_BG =4D4F68
Pressing_Button_FG =E9E9F4
Pressing_Button_BG =3A3C4E
Selected_Button =00BF76
Miscellaneous_BG =3A3C4E
Miscellaneous_Hover_BG =3A3C4E
Preserve_1 =FFFFFF