#!/usr/bin/env python3

import subprocess
import os

d = subprocess.check_output(f'rofi -sep "|" -dmenu -i -p "Message" -location 0 -yoffset -250 -columns 1 -width 20 -hide-scrollbar -line-padding 4 -padding 20 -lines 0 <<< ""', shell=True).decode("utf-8").strip()

os.system(f"polyfy \"{d}\"")
