#! /bin/sh

# i=1
# for monitor in $(bspc query -M); do
  # bspc monitor $monitor \
    # -n "$i" \
    # -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
  # let i++
# done
# NMON=$i
# unset i

# bspc monitor HDMI-1 -d I II III IV V
# bspc monitor eDP-1 -d VI VII VIII IX X

bspc config top_padding 0

bspc config border_width         3
bspc config window_gap          12

# Visual options
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config urgent_border_color "#ff5555"
bspc config focused_locked_border_color "#50fa7b"
bspc config normal_border_color "#bd93f9"
bspc config active_border_color "#caa9fa"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a Matplotlib state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a alsamixer state=floating
bspc rule -a floating_term state=floating center=true rectangle=640x480+0+0
bspc rule -a scratchpad sticky=on state=floating hidden=on

sxhkd &
~/.config/i3/startup.sh &

bspc subscribe node_state | while read -r _ _ _ node state status; do
    if [[ "$state" == "floating" ]]; then
        case "$status" in
            off) xprop -id "$node" -remove _COMPTON_SHADOW;;
            on) xprop -id "$node" -f _COMPTON_SHADOW 32c -set _COMPTON_SHADOW 1;;
        esac
    fi
done &

autorandr --change

if [ "$(bspc query -M | wc -l)" -eq "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV
  bspc monitor $(bspc query -M | sed -n 2p) -d V VI VII
  bspc monitor $(bspc query -M | sed -n 3p) -d VIII IX X
elif [ "$(bspc query -M | wc -l)" -eq "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
else
  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

