#!/bin/bash

#  ____  _   _ 
# |  _ \| \ | | Pradyun Narkadamilli
# | |_) |  \| | https://pradyungn.tech
# |  __/| |\  | MIT License
# |_|   |_| \_| Copyright 2021 Pradyun Narkadamilli

#
# Setup Portion of HLWM config
#

# Function to make commands less annoying
hc() {
    herbstclient "$@"
}

# wmname spoof
wmname LG3D 

# monitor bs
autorandr --change
hc detect_monitors
hc set_attr monitors.0.pad_up 63

# touchpad settings
xinput set-prop "SYNA8004:00 06CB:CD8B Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "SYNA8004:00 06CB:CD8B Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "SYNA8004:00 06CB:CD8B Touchpad" "libinput Click Method Enabled" 0 1

# MPD
if ! pgrep -u $UID -x mpd >/dev/null; then
    mpd &
fi

# MPD MPRIS interface
if ! pgrep -u $UID -x mpDris2 >/dev/null; then
   mpDris2 &
fi

# compton
if ! pgrep picom; then
    picom -b
fi

# Starting MPDNot
if ! pgrep -u $UID -x mpdnot >/dev/null; then
    ~/.config/herbstluftwm/scripts/mpdnot &
fi

# EWW
eww daemon

eww open bar
hc emit_hook reload

xsetroot -solid '#0f0f0f'
feh --bg-fill ~/Pictures/gojo4k.png

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floatcenter=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class="floating_term" floating=on floatplacement=center
hc rule class="feh" floating=on floatplacement=center
hc rule class="Pavucontrol" floating=on floatplacement=center
hc rule class="floating_term" floating=on floatplacement=center
hc rule class="teeny_term" floating=on floatplacement=center
hc rule title="launcher" floating=on floatplacement=center
hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock
