#!/bin/sh

i3lock --nofork -L                	\
    --ignore-empty-password		\
    \
    --indicator				\
    --bar-indicator			\
    --bar-pos="1070"		\
    --bar-base-width="10"		\
    --bar-orientation=horizontal	\
    --bar-color=0f0f0f			\
    --ringver-color=8aac8b		\
    --ringwrong-color=ac8a8c		\
    --bshl-color=ac8a8c			\
    --keyhl-color=aca98a			\
    \
    --clock				\
    --time-str="%I:%M %p"		\
    --time-font="Iosevka"	\
    --time-size=72			\
    --time-pos="1500:920"		\
    --time-color=cacacaff		\
    \
    --date-str="%A, %d %B"		\
    --date-color=cacacaff		\
    --date-font="Iosevka"	\
    --date-size=64			\
    --date-pos="tx:1020"	\
    \
    --verif-font="Iosevka"	\
    --verif-size=72			\
    --verif-text="Processing..."		\
    --verif-color=cacacaff   \
    --wrong-font="Iosevka"	\
    --wrong-size=72			\
    --wrong-text="No Entry!"		\
    --wrong-color=cacacaff   \
    --image=/home/pradyungn/Pictures/moon.jpg
