#!/bin/bash

if [ "$(cat ~/.config/herbstluftwm/remotestat)" -eq 1 ]; then
    echo "0" > ~/.config/herbstluftwm/remotestat;
    notify-send "Controlling Local"
else
    echo "1" > ~/.config/herbstluftwm/remotestat;
    notify-send "Controlling Remote"
fi
